'use client'

import { useState, useEffect, ChangeEvent } from 'react'
import toast from 'react-hot-toast'
import { Button, Card, Badge, Modal, Input } from '@/components/ui'
import { apiGet, apiPost, apiPut, apiDelete } from '@/lib/api'
import { formatDateTime } from '@/lib/utils'

interface UserPoints { id: number; user_id: number; username: string; points: number; total_earn: number; total_used: number; updated_at: string }
interface PointsLog { id: number; user_id: number; username: string; type: string; points: number; balance: number; order_no: string; remark: string; created_at: string }
interface PointsRule { id: number; name: string; type: string; points: number; ratio: number; min_amount: number; max_points: number; status: number; description: string; created_at: string; updated_at: string }

export function PointsPage() {
  const [activeTab, setActiveTab] = useState<'users' | 'logs' | 'rules'>('users')
  const [users, setUsers] = useState<UserPoints[]>([])
  const [logs, setLogs] = useState<PointsLog[]>([])
  const [rules, setRules] = useState<PointsRule[]>([])
  const [loading, setLoading] = useState(true)
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)
  const pageSize = 20
  const [showAdjustModal, setShowAdjustModal] = useState(false)
  const [selectedUser, setSelectedUser] = useState<UserPoints | null>(null)
  const [adjustForm, setAdjustForm] = useState({ points: '', remark: '' })
  const [showRuleModal, setShowRuleModal] = useState(false)
  const [editingRule, setEditingRule] = useState<PointsRule | null>(null)
  const [ruleForm, setRuleForm] = useState({ name: '', type: 'order', points: '', ratio: '', min_amount: '', max_points: '', status: 1, description: '' })
  const [searchKeyword, setSearchKeyword] = useState('')

  useEffect(() => { loadData() }, [activeTab, page])

  const loadData = async () => { setLoading(true); if (activeTab === 'users') await loadUsers(); else if (activeTab === 'logs') await loadLogs(); else await loadRules(); setLoading(false) }
  const loadUsers = async () => { const res = await apiGet<{ users: UserPoints[]; total: number }>(`/api/admin/points/users?page=${page}&page_size=${pageSize}&keyword=${searchKeyword}`); if (res.success) { setUsers(res.users || []); setTotal(res.total || 0) } }
  const loadLogs = async () => { const res = await apiGet<{ logs: PointsLog[]; total: number }>(`/api/admin/points/logs?page=${page}&page_size=${pageSize}`); if (res.success) { setLogs(res.logs || []); setTotal(res.total || 0) } }
  const loadRules = async () => { const res = await apiGet<{ rules: PointsRule[] }>('/api/admin/points/rules'); if (res.success) setRules(res.rules || []) }
  const openAdjustModal = (user: UserPoints) => { setSelectedUser(user); setAdjustForm({ points: '', remark: '' }); setShowAdjustModal(true) }
  const handleAdjust = async () => { if (!selectedUser) return; const points = parseInt(adjustForm.points); if (isNaN(points) || points === 0) { toast.error('请输入有效积分值'); return }; const res = await apiPost('/api/admin/points/adjust', { user_id: selectedUser.user_id, points, remark: adjustForm.remark || '管理员调整' }); if (res.success) { toast.success('积分调整成功'); setShowAdjustModal(false); loadUsers() } else toast.error(res.error || '操作失败') }
  const openRuleModal = (rule?: PointsRule) => { if (rule) { setEditingRule(rule); setRuleForm({ name: rule.name, type: rule.type, points: rule.points.toString(), ratio: rule.ratio.toString(), min_amount: rule.min_amount.toString(), max_points: rule.max_points.toString(), status: rule.status, description: rule.description }) } else { setEditingRule(null); setRuleForm({ name: '', type: 'order', points: '', ratio: '', min_amount: '', max_points: '', status: 1, description: '' }) }; setShowRuleModal(true) }
  const handleSaveRule = async () => { if (!ruleForm.name.trim()) { toast.error('请输入规则名称'); return }; const data = { name: ruleForm.name, type: ruleForm.type, points: parseInt(ruleForm.points) || 0, ratio: parseFloat(ruleForm.ratio) || 0, min_amount: parseFloat(ruleForm.min_amount) || 0, max_points: parseInt(ruleForm.max_points) || 0, status: ruleForm.status, description: ruleForm.description }; const res = editingRule ? await apiPut(`/api/admin/points/rule/${editingRule.id}`, data) : await apiPost('/api/admin/points/rule', data); if (res.success) { toast.success(editingRule ? '更新成功' : '创建成功'); setShowRuleModal(false); loadRules() } else toast.error(res.error || '操作失败') }
  const handleDeleteRule = async (rule: PointsRule) => { if (!confirm(`确定要删除规则"${rule.name}"吗？`)) return; const res = await apiDelete(`/api/admin/points/rule/${rule.id}`); if (res.success) { toast.success('删除成功'); loadRules() } else toast.error(res.error || '删除失败') }
  const handleSearch = () => { setPage(1); loadUsers() }
  const getTypeLabel = (type: string) => { const types: Record<string, { label: string; variant: 'success' | 'danger' | 'warning' | 'info' }> = { earn: { label: '获得', variant: 'success' }, use: { label: '使用', variant: 'danger' }, expire: { label: '过期', variant: 'warning' }, admin: { label: '调整', variant: 'info' } }; return types[type] || { label: type, variant: 'info' as const } }
  const getRuleTypeLabel = (type: string) => ({ order: '订单消费', register: '注册奖励', daily: '每日签到' }[type] || type)
  const totalPages = Math.ceil(total / pageSize)

  if (loading && users.length === 0 && logs.length === 0 && rules.length === 0) return <div className="flex items-center justify-center py-12"><i className="fas fa-spinner fa-spin text-2xl text-primary-400" /></div>

  return (
    <div className="space-y-6">
      <div className="flex gap-2 border-b border-dark-700/50 pb-4">
        <button onClick={() => { setActiveTab('users'); setPage(1) }} className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'users' ? 'bg-primary-500/20 text-primary-400' : 'text-dark-400 hover:text-dark-200 hover:bg-dark-700/50'}`}><i className="fas fa-users mr-2" />用户积分</button>
        <button onClick={() => { setActiveTab('logs'); setPage(1) }} className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'logs' ? 'bg-primary-500/20 text-primary-400' : 'text-dark-400 hover:text-dark-200 hover:bg-dark-700/50'}`}><i className="fas fa-history mr-2" />积分记录</button>
        <button onClick={() => { setActiveTab('rules'); setPage(1) }} className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'rules' ? 'bg-primary-500/20 text-primary-400' : 'text-dark-400 hover:text-dark-200 hover:bg-dark-700/50'}`}><i className="fas fa-cog mr-2" />积分规则</button>
      </div>
      {activeTab === 'users' && <Card title="用户积分" icon={<i className="fas fa-star" />}><div className="flex gap-2 mb-4"><Input placeholder="搜索用户名" value={searchKeyword} onChange={(e: ChangeEvent<HTMLInputElement>) => setSearchKeyword(e.target.value)} className="flex-1" /><Button onClick={handleSearch}><i className="fas fa-search mr-1" />搜索</Button></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-dark-400 text-sm border-b border-dark-700"><th className="pb-3 font-medium">用户</th><th className="pb-3 font-medium">当前积分</th><th className="pb-3 font-medium">累计获得</th><th className="pb-3 font-medium">累计使用</th><th className="pb-3 font-medium">更新时间</th><th className="pb-3 font-medium">操作</th></tr></thead><tbody className="text-dark-200">{users.map((item) => (<tr key={item.id} className="border-b border-dark-700/50"><td className="py-3">{item.username}</td><td className="py-3 text-yellow-400 font-medium">{item.points.toLocaleString()}</td><td className="py-3 text-green-400">+{item.total_earn.toLocaleString()}</td><td className="py-3 text-red-400">-{item.total_used.toLocaleString()}</td><td className="py-3 text-sm text-dark-400">{formatDateTime(item.updated_at)}</td><td className="py-3"><Button size="sm" variant="ghost" onClick={() => openAdjustModal(item)}><i className="fas fa-edit mr-1" />调整</Button></td></tr>))}</tbody></table></div>{totalPages > 1 && <div className="flex justify-center gap-2 mt-4"><Button size="sm" variant="ghost" disabled={page === 1} onClick={() => setPage(p => p - 1)}>上一页</Button><span className="px-4 py-2 text-dark-400">{page} / {totalPages}</span><Button size="sm" variant="ghost" disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}>下一页</Button></div>}</Card>}
      {activeTab === 'logs' && <Card title="积分记录" icon={<i className="fas fa-history" />}><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-dark-400 text-sm border-b border-dark-700"><th className="pb-3 font-medium">用户</th><th className="pb-3 font-medium">类型</th><th className="pb-3 font-medium">积分变动</th><th className="pb-3 font-medium">变动后余额</th><th className="pb-3 font-medium">关联订单</th><th className="pb-3 font-medium">备注</th><th className="pb-3 font-medium">时间</th></tr></thead><tbody className="text-dark-200">{logs.map((log) => { const typeInfo = getTypeLabel(log.type); return (<tr key={log.id} className="border-b border-dark-700/50"><td className="py-3">{log.username}</td><td className="py-3"><Badge variant={typeInfo.variant}>{typeInfo.label}</Badge></td><td className={`py-3 font-medium ${log.points >= 0 ? 'text-green-400' : 'text-red-400'}`}>{log.points >= 0 ? '+' : ''}{log.points.toLocaleString()}</td><td className="py-3">{log.balance.toLocaleString()}</td><td className="py-3 text-sm text-dark-400">{log.order_no || '-'}</td><td className="py-3 text-dark-400 max-w-xs truncate">{log.remark || '-'}</td><td className="py-3 text-sm text-dark-400">{formatDateTime(log.created_at)}</td></tr>)})}</tbody></table></div>{totalPages > 1 && <div className="flex justify-center gap-2 mt-4"><Button size="sm" variant="ghost" disabled={page === 1} onClick={() => setPage(p => p - 1)}>上一页</Button><span className="px-4 py-2 text-dark-400">{page} / {totalPages}</span><Button size="sm" variant="ghost" disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}>下一页</Button></div>}</Card>}
      {activeTab === 'rules' && <Card title="积分规则" icon={<i className="fas fa-cog" />} action={<Button size="sm" onClick={() => openRuleModal()}><i className="fas fa-plus mr-1" />添加规则</Button>}><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-dark-400 text-sm border-b border-dark-700"><th className="pb-3 font-medium">规则名称</th><th className="pb-3 font-medium">类型</th><th className="pb-3 font-medium">固定积分</th><th className="pb-3 font-medium">积分比例</th><th className="pb-3 font-medium">最低消费</th><th className="pb-3 font-medium">单次上限</th><th className="pb-3 font-medium">状态</th><th className="pb-3 font-medium">操作</th></tr></thead><tbody className="text-dark-200">{rules.map((rule) => (<tr key={rule.id} className="border-b border-dark-700/50"><td className="py-3">{rule.name}</td><td className="py-3"><Badge variant="info">{getRuleTypeLabel(rule.type)}</Badge></td><td className="py-3">{rule.points > 0 ? rule.points : '-'}</td><td className="py-3">{rule.ratio > 0 ? `${rule.ratio}倍` : '-'}</td><td className="py-3">{rule.min_amount > 0 ? `¥${rule.min_amount}` : '-'}</td><td className="py-3">{rule.max_points > 0 ? rule.max_points : '不限'}</td><td className="py-3"><Badge variant={rule.status === 1 ? 'success' : 'danger'}>{rule.status === 1 ? '启用' : '禁用'}</Badge></td><td className="py-3"><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => openRuleModal(rule)}><i className="fas fa-edit" /></Button><Button size="sm" variant="ghost" className="text-red-400" onClick={() => handleDeleteRule(rule)}><i className="fas fa-trash" /></Button></div></td></tr>))}</tbody></table></div></Card>}
      <Modal isOpen={showAdjustModal} onClose={() => setShowAdjustModal(false)} title={`调整积分 - ${selectedUser?.username}`}><div className="space-y-4"><div className="p-3 bg-dark-700/30 rounded-lg"><div className="text-sm text-dark-400">当前积分</div><div className="text-xl font-bold text-yellow-400">{selectedUser?.points.toLocaleString() || 0}</div></div><Input label="积分变动" type="number" placeholder="正数增加，负数减少" value={adjustForm.points} onChange={(e: ChangeEvent<HTMLInputElement>) => setAdjustForm({ ...adjustForm, points: e.target.value })} /><Input label="备注" placeholder="请输入备注（可选）" value={adjustForm.remark} onChange={(e: ChangeEvent<HTMLInputElement>) => setAdjustForm({ ...adjustForm, remark: e.target.value })} /><Button className="w-full" onClick={handleAdjust}>确认调整</Button></div></Modal>
      <Modal isOpen={showRuleModal} onClose={() => setShowRuleModal(false)} title={editingRule ? '编辑规则' : '添加规则'}><div className="space-y-4"><Input label="规则名称" placeholder="请输入规则名称" value={ruleForm.name} onChange={(e: ChangeEvent<HTMLInputElement>) => setRuleForm({ ...ruleForm, name: e.target.value })} /><div><label className="block text-sm font-medium text-dark-300 mb-2">规则类型</label><select value={ruleForm.type} onChange={(e) => setRuleForm({ ...ruleForm, type: e.target.value })} className="w-full px-3 py-2 bg-dark-700 border border-dark-600 rounded-lg text-dark-200" disabled={!!editingRule}><option value="order">订单消费</option><option value="register">注册奖励</option><option value="daily">每日签到</option></select></div><div className="grid grid-cols-2 gap-4"><Input label="固定积分" type="number" placeholder="0" value={ruleForm.points} onChange={(e: ChangeEvent<HTMLInputElement>) => setRuleForm({ ...ruleForm, points: e.target.value })} /><Input label="积分比例" type="number" placeholder="如：10" value={ruleForm.ratio} onChange={(e: ChangeEvent<HTMLInputElement>) => setRuleForm({ ...ruleForm, ratio: e.target.value })} /></div><div className="grid grid-cols-2 gap-4"><Input label="最低消费金额" type="number" placeholder="0" value={ruleForm.min_amount} onChange={(e: ChangeEvent<HTMLInputElement>) => setRuleForm({ ...ruleForm, min_amount: e.target.value })} /><Input label="单次积分上限" type="number" placeholder="0表示不限" value={ruleForm.max_points} onChange={(e: ChangeEvent<HTMLInputElement>) => setRuleForm({ ...ruleForm, max_points: e.target.value })} /></div><div><label className="block text-sm font-medium text-dark-300 mb-2">状态</label><div className="flex gap-2"><button onClick={() => setRuleForm({ ...ruleForm, status: 1 })} className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors ${ruleForm.status === 1 ? 'bg-green-500/20 text-green-400 border border-green-500/50' : 'bg-dark-700/50 text-dark-400 border border-dark-600'}`}>启用</button><button onClick={() => setRuleForm({ ...ruleForm, status: 0 })} className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors ${ruleForm.status === 0 ? 'bg-red-500/20 text-red-400 border border-red-500/50' : 'bg-dark-700/50 text-dark-400 border border-dark-600'}`}>禁用</button></div></div><Input label="规则描述" placeholder="请输入规则描述（可选）" value={ruleForm.description} onChange={(e: ChangeEvent<HTMLInputElement>) => setRuleForm({ ...ruleForm, description: e.target.value })} /><Button className="w-full" onClick={handleSaveRule}>{editingRule ? '保存修改' : '创建规则'}</Button></div></Modal>
    </div>
  )
}
