'use client'

import { useState, useEffect, ChangeEvent } from 'react'
import toast from 'react-hot-toast'
import { Button, Card, Badge, Modal, Input } from '@/components/ui'
import { apiGet, apiPost, apiPut, apiDelete } from '@/lib/api'
import { formatDateTime } from '@/lib/utils'

interface ScheduledTask { id: number; name: string; type: string; cron_expr: string; config: string; status: number; last_run_at: string | null; next_run_at: string | null; last_result: string; run_count: number; fail_count: number; description: string; created_at: string; updated_at: string }
interface TaskLog { id: number; task_id: number; task_name: string; status: string; duration: number; result: string; error: string; created_at: string }
interface TaskType { type: string; name: string; description: string }
interface TaskStats { total: number; enabled: number; disabled: number; today_runs: number; today_success: number; today_failed: number }

export function TasksPage() {
  const [activeTab, setActiveTab] = useState<'tasks' | 'logs'>('tasks')
  const [tasks, setTasks] = useState<ScheduledTask[]>([])
  const [logs, setLogs] = useState<TaskLog[]>([])
  const [taskTypes, setTaskTypes] = useState<TaskType[]>([])
  const [stats, setStats] = useState<TaskStats | null>(null)
  const [loading, setLoading] = useState(true)
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)
  const pageSize = 20
  const [showTaskModal, setShowTaskModal] = useState(false)
  const [editingTask, setEditingTask] = useState<ScheduledTask | null>(null)
  const [taskForm, setTaskForm] = useState({ name: '', type: '', cron_expr: '', config: '', status: 1, description: '' })
  const [logTaskId, setLogTaskId] = useState(0)

  useEffect(() => { loadTaskTypes(); loadStats() }, [])
  useEffect(() => { loadData() }, [activeTab, page, logTaskId])

  const loadData = async () => { setLoading(true); if (activeTab === 'tasks') await loadTasks(); else await loadLogs(); setLoading(false) }
  const loadTasks = async () => { const res = await apiGet<{ tasks: ScheduledTask[] }>('/api/admin/tasks'); if (res.success) setTasks(res.tasks || []) }
  const loadLogs = async () => { const res = await apiGet<{ logs: TaskLog[]; total: number }>(`/api/admin/tasks/logs?task_id=${logTaskId}&page=${page}&page_size=${pageSize}`); if (res.success) { setLogs(res.logs || []); setTotal(res.total || 0) } }
  const loadTaskTypes = async () => { const res = await apiGet<{ types: TaskType[] }>('/api/admin/tasks/types'); if (res.success) setTaskTypes(res.types || []) }
  const loadStats = async () => { const res = await apiGet<{ stats: TaskStats }>('/api/admin/tasks/stats'); if (res.success) setStats(res.stats || null) }
  const openTaskModal = (task?: ScheduledTask) => { if (task) { setEditingTask(task); setTaskForm({ name: task.name, type: task.type, cron_expr: task.cron_expr, config: task.config, status: task.status, description: task.description }) } else { setEditingTask(null); setTaskForm({ name: '', type: taskTypes[0]?.type || '', cron_expr: '0 0 * * *', config: '', status: 1, description: '' }) }; setShowTaskModal(true) }
  const handleSaveTask = async () => { if (!taskForm.name.trim()) { toast.error('请输入任务名称'); return }; if (!taskForm.type) { toast.error('请选择任务类型'); return }; const res = editingTask ? await apiPut(`/api/admin/task/${editingTask.id}`, taskForm) : await apiPost('/api/admin/task', taskForm); if (res.success) { toast.success(editingTask ? '更新成功' : '创建成功'); setShowTaskModal(false); loadTasks(); loadStats() } else toast.error(res.error || '操作失败') }
  const handleDeleteTask = async (task: ScheduledTask) => { if (!confirm(`确定要删除任务"${task.name}"吗？`)) return; const res = await apiDelete(`/api/admin/task/${task.id}`); if (res.success) { toast.success('删除成功'); loadTasks(); loadStats() } else toast.error(res.error || '删除失败') }
  const handleToggleStatus = async (task: ScheduledTask) => { const res = await apiPost(`/api/admin/task/${task.id}/toggle`, {}); if (res.success) { toast.success('状态已更新'); loadTasks(); loadStats() } else toast.error(res.error || '操作失败') }
  const handleRunNow = async (task: ScheduledTask) => { const res = await apiPost(`/api/admin/task/${task.id}/run`, {}); if (res.success) { toast.success('任务已开始执行'); setTimeout(() => { loadTasks(); loadLogs() }, 1000) } else toast.error(res.error || '执行失败') }
  const getTypeName = (type: string) => taskTypes.find(t => t.type === type)?.name || type
  const totalPages = Math.ceil(total / pageSize)

  if (loading && tasks.length === 0 && logs.length === 0) return <div className="flex items-center justify-center py-12"><i className="fas fa-spinner fa-spin text-2xl text-primary-400" /></div>

  return (
    <div className="space-y-6">
      {stats && <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4"><div className="bg-dark-800/50 rounded-lg p-4 border border-dark-700/50"><div className="text-2xl font-bold text-dark-100">{stats.total}</div><div className="text-sm text-dark-400">总任务数</div></div><div className="bg-dark-800/50 rounded-lg p-4 border border-dark-700/50"><div className="text-2xl font-bold text-green-400">{stats.enabled}</div><div className="text-sm text-dark-400">已启用</div></div><div className="bg-dark-800/50 rounded-lg p-4 border border-dark-700/50"><div className="text-2xl font-bold text-dark-500">{stats.disabled}</div><div className="text-sm text-dark-400">已禁用</div></div><div className="bg-dark-800/50 rounded-lg p-4 border border-dark-700/50"><div className="text-2xl font-bold text-blue-400">{stats.today_runs}</div><div className="text-sm text-dark-400">今日执行</div></div><div className="bg-dark-800/50 rounded-lg p-4 border border-dark-700/50"><div className="text-2xl font-bold text-green-400">{stats.today_success}</div><div className="text-sm text-dark-400">今日成功</div></div><div className="bg-dark-800/50 rounded-lg p-4 border border-dark-700/50"><div className="text-2xl font-bold text-red-400">{stats.today_failed}</div><div className="text-sm text-dark-400">今日失败</div></div></div>}
      <div className="flex gap-2 border-b border-dark-700/50 pb-4"><button onClick={() => { setActiveTab('tasks'); setPage(1) }} className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'tasks' ? 'bg-primary-500/20 text-primary-400' : 'text-dark-400 hover:text-dark-200 hover:bg-dark-700/50'}`}><i className="fas fa-tasks mr-2" />任务列表</button><button onClick={() => { setActiveTab('logs'); setPage(1) }} className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${activeTab === 'logs' ? 'bg-primary-500/20 text-primary-400' : 'text-dark-400 hover:text-dark-200 hover:bg-dark-700/50'}`}><i className="fas fa-history mr-2" />执行日志</button></div>
      {activeTab === 'tasks' && <Card title="定时任务" icon={<i className="fas fa-clock" />} action={<Button size="sm" onClick={() => openTaskModal()}><i className="fas fa-plus mr-1" />添加任务</Button>}><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-dark-400 text-sm border-b border-dark-700"><th className="pb-3 font-medium">任务名称</th><th className="pb-3 font-medium">类型</th><th className="pb-3 font-medium">Cron表达式</th><th className="pb-3 font-medium">状态</th><th className="pb-3 font-medium">上次执行</th><th className="pb-3 font-medium">下次执行</th><th className="pb-3 font-medium">执行统计</th><th className="pb-3 font-medium">操作</th></tr></thead><tbody className="text-dark-200">{tasks.map((task) => (<tr key={task.id} className="border-b border-dark-700/50"><td className="py-3"><div className="font-medium">{task.name}</div>{task.description && <div className="text-xs text-dark-400 mt-1">{task.description}</div>}</td><td className="py-3"><Badge variant="info">{getTypeName(task.type)}</Badge></td><td className="py-3 font-mono text-sm">{task.cron_expr || '-'}</td><td className="py-3"><Badge variant={task.status === 1 ? 'success' : 'danger'}>{task.status === 1 ? '启用' : '禁用'}</Badge></td><td className="py-3 text-sm text-dark-400">{task.last_run_at ? formatDateTime(task.last_run_at) : '-'}{task.last_result && <div className={`text-xs mt-1 ${task.last_result === 'success' ? 'text-green-400' : 'text-red-400'}`}>{task.last_result === 'success' ? '成功' : '失败'}</div>}</td><td className="py-3 text-sm text-dark-400">{task.next_run_at ? formatDateTime(task.next_run_at) : '-'}</td><td className="py-3"><span className="text-green-400">{task.run_count}</span><span className="text-dark-500 mx-1">/</span><span className="text-red-400">{task.fail_count}</span></td><td className="py-3"><div className="flex gap-1"><Button size="sm" variant="ghost" onClick={() => handleRunNow(task)} title="立即执行"><i className="fas fa-play text-green-400" /></Button><Button size="sm" variant="ghost" onClick={() => handleToggleStatus(task)} title={task.status === 1 ? '禁用' : '启用'}><i className={`fas fa-${task.status === 1 ? 'pause' : 'play'}`} /></Button><Button size="sm" variant="ghost" onClick={() => openTaskModal(task)}><i className="fas fa-edit" /></Button><Button size="sm" variant="ghost" className="text-red-400" onClick={() => handleDeleteTask(task)}><i className="fas fa-trash" /></Button></div></td></tr>))}</tbody></table></div></Card>}
      {activeTab === 'logs' && <Card title="执行日志" icon={<i className="fas fa-history" />}><div className="flex gap-2 mb-4"><select value={logTaskId} onChange={(e) => { setLogTaskId(parseInt(e.target.value)); setPage(1) }} className="px-3 py-2 bg-dark-700 border border-dark-600 rounded-lg text-dark-200"><option value={0}>全部任务</option>{tasks.map(task => <option key={task.id} value={task.id}>{task.name}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full"><thead><tr className="text-left text-dark-400 text-sm border-b border-dark-700"><th className="pb-3 font-medium">任务名称</th><th className="pb-3 font-medium">执行状态</th><th className="pb-3 font-medium">耗时</th><th className="pb-3 font-medium">执行结果</th><th className="pb-3 font-medium">执行时间</th></tr></thead><tbody className="text-dark-200">{logs.map((log) => (<tr key={log.id} className="border-b border-dark-700/50"><td className="py-3">{log.task_name}</td><td className="py-3"><Badge variant={log.status === 'success' ? 'success' : 'danger'}>{log.status === 'success' ? '成功' : '失败'}</Badge></td><td className="py-3 text-sm">{log.duration}ms</td><td className="py-3 text-sm text-dark-400 max-w-xs truncate">{log.error || log.result || '-'}</td><td className="py-3 text-sm text-dark-400">{formatDateTime(log.created_at)}</td></tr>))}</tbody></table></div>{totalPages > 1 && <div className="flex justify-center gap-2 mt-4"><Button size="sm" variant="ghost" disabled={page === 1} onClick={() => setPage(p => p - 1)}>上一页</Button><span className="px-4 py-2 text-dark-400">{page} / {totalPages}</span><Button size="sm" variant="ghost" disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}>下一页</Button></div>}</Card>}
      <Modal isOpen={showTaskModal} onClose={() => setShowTaskModal(false)} title={editingTask ? '编辑任务' : '添加任务'}><div className="space-y-4"><Input label="任务名称" placeholder="请输入任务名称" value={taskForm.name} onChange={(e: ChangeEvent<HTMLInputElement>) => setTaskForm({ ...taskForm, name: e.target.value })} /><div><label className="block text-sm font-medium text-dark-300 mb-2">任务类型</label><select value={taskForm.type} onChange={(e) => setTaskForm({ ...taskForm, type: e.target.value })} className="w-full px-3 py-2 bg-dark-700 border border-dark-600 rounded-lg text-dark-200" disabled={!!editingTask}><option value="">请选择任务类型</option>{taskTypes.map(type => <option key={type.type} value={type.type}>{type.name}</option>)}</select>{taskTypes.find(t => t.type === taskForm.type)?.description && <div className="text-xs text-dark-400 mt-1">{taskTypes.find(t => t.type === taskForm.type)?.description}</div>}</div><div><Input label="Cron表达式" placeholder="如：0 0 * * *（每天0点执行）" value={taskForm.cron_expr} onChange={(e: ChangeEvent<HTMLInputElement>) => setTaskForm({ ...taskForm, cron_expr: e.target.value })} /><div className="text-xs text-dark-400 mt-1">格式：分 时 日 月 周（如：0 2 * * * 表示每天凌晨2点）</div></div><div><label className="block text-sm font-medium text-dark-300 mb-2">任务配置（JSON）</label><textarea value={taskForm.config} onChange={(e) => setTaskForm({ ...taskForm, config: e.target.value })} className="w-full px-3 py-2 bg-dark-700 border border-dark-600 rounded-lg text-dark-200 h-24 font-mono text-sm" placeholder='{"key": "value"}' /></div><div><label className="block text-sm font-medium text-dark-300 mb-2">状态</label><div className="flex gap-2"><button onClick={() => setTaskForm({ ...taskForm, status: 1 })} className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors ${taskForm.status === 1 ? 'bg-green-500/20 text-green-400 border border-green-500/50' : 'bg-dark-700/50 text-dark-400 border border-dark-600'}`}>启用</button><button onClick={() => setTaskForm({ ...taskForm, status: 0 })} className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors ${taskForm.status === 0 ? 'bg-red-500/20 text-red-400 border border-red-500/50' : 'bg-dark-700/50 text-dark-400 border border-dark-600'}`}>禁用</button></div></div><Input label="任务描述" placeholder="请输入任务描述（可选）" value={taskForm.description} onChange={(e: ChangeEvent<HTMLInputElement>) => setTaskForm({ ...taskForm, description: e.target.value })} /><Button className="w-full" onClick={handleSaveTask}>{editingTask ? '保存修改' : '创建任务'}</Button></div></Modal>
    </div>
  )
}
